apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: go-oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: go-oauth2-server-api
          image: k3d-registry.tashima.space:5345/tashima42/go-oauth2-server/api
          imagePullPolicy: "Always"
          env:
            - name: TZ
              value: "GMT-3"
            - name: DB_USER
              value: outtakes
            - name: DB_NAME
              value: postgres
            - name: DB_HOST
              value: database-cluster-ip-service
            - name: DB_PORT
              value: '5432'
            - name: GIN_MODE
              value: release
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: JWTSECRET