apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: go-oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: ghcr.io/tashima42/go-oauth2-server:main
          imagePullPolicy: "Always"
          env:
            - name: TZ
              value: "GMT-3"
            - name: ARGS
              value: api
            - name: DB_USER
              value: outtakes
            - name: DB_NAME
              value: postgres
            - name: DB_HOST
              value: postgres-cluster-ip-service
            - name: DB_PORT
              value: '5432'
            - name: GIN_MODE
              value: release
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegramtoken
                  key: TELEGRAM_TOKEN