apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: go-oauth2-server-local
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_USER
              value: outtakes
            - name: POSTGRES_DB
              value: postgres
            - name: TZ
              value: "GMT-3"
            - name: PGTZ
              value: "GMT-3"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
