#!/bin/bash

ENV={ENVIROMENT:=-dev}

if ! command -v k3d &> /dev/null
then
    echo "k3d could not be found, please install it before continuing"
    exit
fi

if ! command -v skaffold &> /dev/null
then
    echo "skaffold could not be found, please install it before continuing"
    exit
fi

if ! command -v kubectl &> /dev/null
then
    echo "kubectl could not be found, please install it before continuing"
    exit
fi

echo "creating k3d cluster"
k3d cluster create $ENV
echo "setting skaffold to use local cluster"
skaffold config set --global local-cluster true