#!/bin/bash

DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

migrate \
  -path ${MIGRATE_DIR:-$DIR/../db/schema_migrations} \
  -database postgres://${PGUSER:-outtakes}:${PGPASSWORD:-password}@${PGHOST:-localhost}:${PGPORT:-5432}/postgres?sslmode=disable \
  $@